### ISSUE TITLE
BeautySearch fails to start when connected over remote desktop

### ISSUE THREAD

**Issue by valinet** [krlvm/BeautySearch#43]
This is a pretty common scenario: when connected via remote desktop connection, BeautySearch cannot start. Instead, the common unhandled exception dialog is displayed, with this message:

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentNullException: Value cannot be null.
Parameter name: name
   at System.Security.Principal.NTAccount..ctor(String name)
   at BeautySearch.ScriptInstaller.get_SID()
   at BeautySearch.Utility.OpenCurrentUserRegistryKey(String key, Boolean writable)
   at BeautySearch.Utility.IsPersonalizationFeatureEnabled(String feature)
   at BeautySearch.InstallationForm.EnumerateFeatures()
   at BeautySearch.InstallationForm.InstallationForm_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4614.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
BeautySearch
    Assembly Version: 1.15.2.0
    Win32 Version: 1.15.2.0
    CodeBase: file:///C:/Users/root/Downloads/BeautySearch.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4550.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4605.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4435.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4605.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

Only by looking at that, it hints that an attempt is made to build up an object wrapping a Windows user account using an invalid name, for example, starting from an empty string. Of course, since the software is open, I checked it out locally and compiled it myself to see where it fails in the debugger. The problem occurs here:

https://github.com/krlvm/BeautySearch/blob/6f6710389e1e094dcedf693687bd253d96f42f1b/BeautySearch/Installer/ScriptInstaller.cs#L500

What happens at runtime is that `username` is empty on my machine. I then looked on the implementation of `Utility.GetUsername()`, which seems to be the "setter' for the username string. The contents is one of the answers from this popular StackOverflow question: https://stackoverflow.com/a/48317239

As mentioned there, there are a million ways to do this, so much so that it is hard to pick the right one... This one that you chose has the disadvantage that it requires WMI to be available (some users may disable the service), and also that the database is proper, and not corrupt. Also, the call simply seems to fail when the user is connected via remote desktop. You can also see this in PowerShell when using the `Get-WMIObject` cmdlet while connected remotely:

```
Get-WMIObject -class Win32_ComputerSystem Username
```

I did not find any documentation regarding this behavior. There are indeed other people that mention it and ask why it happens so, but as is generally the case with Microsoft, and their useless support forum in particular, no one knew anything: https://learn.microsoft.com/en-us/answers/questions/349657/get-wmiobject-win32-computersystem-username-return

So, yeah, if I were to code this, I'd stick to Win32 API calls which are the primary source and well documented and tested over the years. I dislike these wrappers that many people trust bu fail weirdly in some of these edge case scenarios... I don't know, maybe you view it differently, that's why I haven't opened a PR, and instead opt to suggest here an implementation which should replace the `Utility::GetUsername` function from here: https://github.com/krlvm/BeautySearch/blob/6f6710389e1e094dcedf693687bd253d96f42f1b/BeautySearch/Utility.cs#L137

```cpp
        [DllImport("kernel32.dll", SetLastError = true)]
        [ReliabilityContract(Consistency.WillNotCorruptState, Cer.Success)]
        [SuppressUnmanagedCodeSecurity]
        [return: MarshalAs(UnmanagedType.Bool)]
        static extern bool CloseHandle(IntPtr hObject);
        [DllImport("kernel32.dll", SetLastError = true)]
        public static extern IntPtr GetCurrentProcess();
        public const UInt32 TOKEN_QUERY = 0x0008;
        [DllImport("advapi32.dll", SetLastError = true)]
        [return: MarshalAs(UnmanagedType.Bool)]
        static extern bool OpenProcessToken(IntPtr ProcessHandle, UInt32 DesiredAccess, out IntPtr TokenHandle);
        public const UInt32 TokenUser = 1;
        [DllImport("advapi32.dll", SetLastError = true)]
        static extern bool GetTokenInformation(IntPtr TokenHandle, UInt32 TokenInformationClass, IntPtr TokenInformation, uint TokenInformationLength, out uint ReturnLength);
        public struct TOKEN_USER
        {
            public SID_AND_ATTRIBUTES User;
        }

        [StructLayout(LayoutKind.Sequential)]
        public struct SID_AND_ATTRIBUTES
        {

            public IntPtr Sid;
            public int Attributes;
        }
        [DllImport("advapi32.dll", CharSet = CharSet.Auto, SetLastError = true)]
        static extern bool LookupAccountSid(string lpSystemName, IntPtr Sid, StringBuilder lpName, ref uint cchName, StringBuilder ReferencedDomainName, ref uint cchReferencedDomainName, out uint peUse);

        public static string GetUsername()
        {
            string rv = null;
            var hProcess = GetCurrentProcess();
            if (hProcess != IntPtr.Zero)
            {
                IntPtr hToken = IntPtr.Zero;
                if (OpenProcessToken(hProcess, TOKEN_QUERY, out hToken) && hToken != IntPtr.Zero)
                {
                    uint lenTokenInfo = 0;
                    GetTokenInformation(hToken, TokenUser, IntPtr.Zero, lenTokenInfo, out lenTokenInfo);
                    if (lenTokenInfo > 0)
                    {
                        IntPtr pTokenInfo = Marshal.AllocHGlobal((int)lenTokenInfo);
                        if (pTokenInfo != IntPtr.Zero)
                        {
                            if (GetTokenInformation(hToken, TokenUser, pTokenInfo, lenTokenInfo, out lenTokenInfo) && lenTokenInfo > 0)
                            {
                                TOKEN_USER TokenUser = (TOKEN_USER)Marshal.PtrToStructure(pTokenInfo, typeof(TOKEN_USER));
                                if (TokenUser.User.Sid != IntPtr.Zero)
                                {
                                    uint peUse = 0;
                                    uint cchName = 0;
                                    uint cchReferencedDomainName = 0;
                                    LookupAccountSid(null, TokenUser.User.Sid, null, ref cchName, null, ref cchReferencedDomainName, out peUse);
                                    if (cchName > 0 && cchReferencedDomainName > 0)
                                    {
                                        StringBuilder strName = new StringBuilder((int)cchName);
                                        StringBuilder strReferencedDomainName = new StringBuilder((int)cchReferencedDomainName);
                                        if (LookupAccountSid(null, TokenUser.User.Sid, strName, ref cchName, strReferencedDomainName, ref cchReferencedDomainName, out peUse) && cchName > 0 && cchReferencedDomainName > 0)
                                        {
                                            rv = strReferencedDomainName + "\\\\" + strName;
                                        }
                                    }
                                }
                            }
                            Marshal.FreeHGlobal(pTokenInfo);
                        }
                    }
                    CloseHandle(hToken);
                }
            }
            if (rv == null)
            {
                throw new Exception("Failed to get your account's user name.");
            }
            return rv;
        }
```

It may look like polluting managed code with C-style stuff, but I believe it being *reliable* outweighs that fact. Anyway, it's your call, I have already applied it on that remote machine and it worked beautifully, so let me take this opportunity to thank you as well for this wonderful program and the research you invested in this topic.

PS. What this should do in case of failure (the `rv == null` check), again, is up for debate... I'd throw an exception and/or even kill the app altogether in that case, if that method fails still, the user has bigger things to worry about than how the search window looks...

**Comment by valinet** [comment]
I am glad that the code was of use. Indeed, what matters the most is the actual functionality of the app. I just happened to notice this and decided it was best, especially given how punctual the problem and fix was, to help with drop-in place code. 

Again, thank you for this amazing application as well.
