### ISSUE TITLE
BeautySearch fails after Update KB5030300 (19045.3516 for 22H2)

### ISSUE THREAD

**Issue by bywkgexmkiltxh** [krlvm/BeautySearch#47]
_Unknown Error: -532462766_

Note: I admit that this build is a Preview build at the moment (September 28, 2023), but since this build will be available for everyone in the near future, I wanted to share this bug.

**Comment by krlvm** [comment]
Does it crash if you disable Controller Integration flag?

**Comment by bywkgexmkiltxh** [comment]
Yes, I unchecked Controller Integration and got the same error.

**Comment by krlvm** [comment]
Can't reproduce on fresh 19045.3516 install with the latest BeautySearch version, it installs without any issues

**Comment by bywkgexmkiltxh** [comment]
Interesting... I uploaded a screen recording to demonstrate the error: https://1drv.ms/v/s!Asuk7rNzpZ00gjyCQ6E-7Jk1luyB?e=cC6cd2

**Comment by krlvm** [comment]
What if you adjust directory permissions manually as described [here](https://github.com/krlvm/BeautySearch/issues/11#issuecomment-860113080)?

**Comment by bywkgexmkiltxh** [comment]
It works now, thank you a lot!
This is unrelated but context menus have black borders with BeautySearch so they look inconsistent, Windows adds white borders to dark context menus
Is there a way to make the borders white just like the rest of the OS such as taskbar context menu?

**Comment by krlvm** [comment]
You need to disable "Fluent Context Menus" option

**Comment by ReginaLain** [comment]
> You need to disable "Fluent Context Menus" option

Unfortunately none of the recommendations helped.
The permissions I gave.
I disabled Fluent Context Menus.
None of this helps. What does help is disabling 
Enable Acrylic, but what's the point without it? Any other ideas? I have LTSC 2021

**Comment by ReginaLain** [comment]
If you run it as administrator, the following error occurs.
`See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at BeautySearch.Installer.FakeBackgroundAcrylic.CaptureWallpaperFragment(Bitmap bitmap, Boolean minimizeWindows, Int32[] sleep, String directory)
   at BeautySearch.Installer.FakeBackgroundAcrylic.CaptureRealDesktop(String directory)
   at BeautySearch.Installer.ScriptInstaller.Install(FeatureControl features)
   at BeautySearch.InstallationForm.installBtn_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
BeautySearch
    Assembly Version: 1.16.0.0
    Win32 Version: 1.16.0.0
    CodeBase: file:///C:/Users/Lain/Downloads/BeautySearch(2).exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9206.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9200.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9206.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.


`

**Comment by ReginaLain** [comment]
Holy shit, guys, I found the cause. It was because I had a glitch in my Microsoft Terminal software. After uninstalling it, everything worked, awesome.

**Comment by bywkgexmkiltxh** [comment]
This is a minor issue so I didn't create a new issue. Context menus are still slightly transparent even when transparency is disabled from Windows settings.
