### ISSUE TITLE
Error -1073741819

### ISSUE THREAD

**Issue by ReginaLain** [krlvm/BeautySearch#48]
When trying to install, I get the following error:
![ошибка 1](https://github.com/krlvm/BeautySearch/assets/20730653/2e474967-74c5-4847-8182-b988cdacc0fd)
If run as administrator, the error looks like this:
![Error2](https://github.com/krlvm/BeautySearch/assets/20730653/3e61a36e-b534-496a-9287-31d885154750)
Details
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

```
************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at BeautySearch.Installer.FakeBackgroundAcrylic.CaptureWallpaperFragment(Bitmap bitmap, Boolean minimizeWindows, Int32[] sleep, String directory)
   at BeautySearch.Installer.FakeBackgroundAcrylic.CaptureRealDesktop(String directory)
   at BeautySearch.Installer.ScriptInstaller.Install(FeatureControl features)
   at BeautySearch.InstallationForm.installBtn_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
BeautySearch
    Assembly Version: 1.16.0.0
    Win32 Version: 1.16.0.0
    CodeBase: file:///C:/Users/lain/Downloads/BeautySearch.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9214.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9214.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9214.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

The permissions for this instruction [](https://github.com/krlvm/BeautySearch/issues/11#issuecomment-860113080) have been granted
On exactly the same build, but on a laptop everything works perfectly, what is the matter?

**Comment by ReginaLain** [comment]
Figured it out, but not 100%.
I did the following - as soon as this error appeared, I went into the display settings and turned off the second monitor, leaving the first one working. This caused TranslucentTB to crash
and Explorer hangs, but BeautySearch installed! I then restarted Explorer and everything worked as it should. No matter how many times I try to reinstall BeautySearch, it does not give an error. So I think there is a connection between the two monitors and TranslucentTB, so if you encounter the same error, try disabling the second monitor first and then, if that doesn't help, disable TranslucentTB temporarily.

**Comment by krlvm** [comment]
> BeautySearch.Installer.FakeBackgroundAcrylic.CaptureWallpaperFragment

Yes, this was related to second monitor.

Which Windows 10 and BeautySearch version you are using?

**Comment by ReginaLain** [comment]
> > BeautySearch.Installer.FakeBackgroundAcrylic.CaptureWallpaperFragment
> 
> Yes, this was related to second monitor.
> 
> Which Windows 10 and BeautySearch version you are using?

Windows 10 21h2 ltsc  build 19044.1288
BeautySearch 1.16.0.0
